### ISSUE TITLE
[FEATURE REQUEST] Deathmatch after maximum Y-level of lava.

### ISSUE THREAD

**Issue by DuckMC** [goodbyepavlyi/LavaRise#10]
### [FEATURE REQUEST] Deathmatch after maximum Y-level of lava.

**Description:** When the lava reaches the maximum Y-level, players must lose half a heart every second. This encourages them to go to each other and start fights so that the game does not stall. 

**Extra addition:** After starting deathmatch, the border starts shrinking, forcing players to go to each other and fight. The player who survives the pvp battle the longest or survives the deathmatch damage the longest wins the game.

**Comment by goodbyepavlyi** [comment]
Thank you for the suggestion! This feature will be included in the upcoming v2.0.5 release.
Commit: 94e5c99c503d847c8fb010ff9307a4bf9d8f68a4
