### ISSUE TITLE
[FEATURE REQUEST] Worldborder to keep players inside the map 

### ISSUE THREAD

**Issue by DuckMC** [goodbyepavlyi/LavaRise#11]
### [FEATURE REQUEST] Worldborder to keep players inside the map 

**Description:** Add a worldborder to the map to prevent players from going outside the boundaries of the playing zone. This ensures that players stay within the playing area and that the game is fair.

**Comment by goodbyepavlyi** [comment]
Thank you for the suggestion! This feature will be included in the upcoming v2.0.1 release, where player movement will be restricted using a PlayerMoveEvent listener instead of a world border.
Commit: e8c3bdc

**Comment by DuckMC** [comment]
Thanks for implementing the requested functionality! Seems like a good solution. I look forward to seeing this feature soon in the upcoming v2.0.1 release.
