### ISSUE TITLE
[FEATURE REQUEST] Configurable Grace Period for pvpEnabled Event

### ISSUE THREAD

**Issue by DuckMC** [goodbyepavlyi/LavaRise#12]
### [FEATURE REQUEST] Configurable Grace Period for pvpEnabled Event

**Description:** I would like to have the ability to set a separate grace period for the `pvpEnabled` event.

This feature would allow administrators to define the duration, in seconds, of a grace period during which players are temporarily immune to PvP combat. The grace period would provide a window of time after PvP is enabled, ensuring that players have a chance to prepare or escape before being vulnerable to combat with other players. This setting would give server administrators more control over the timing and flow of PvP interactions.

**Comment by goodbyepavlyi** [comment]
A grace period for PVP doesn't seem necessary, as `game.gracePhaseTime` already provides players time to prepare for combat, such as gathering blocks and other resources.

**Comment by DuckMC** [comment]
My argument is that it would be useful to set the` lavaPhaseStart` and `pvpEnabled` at different times. By spreading out the events, you create more variety in the game.

For example, if the` lavaPhaseStart` happens before `pvpEnabled` is enabled, players may need to focus on survival and strategically position themselves for the lava challenge before shifting their attention to PvP. This would make the overall game experience more dynamic in my opinion.

**Comment by goodbyepavlyi** [comment]
That is a valid point, this feature will be included in the upcoming v2.0.3 release.
Commit: https://github.com/goodbyepavlyi/LavaRise/commit/1864a0eb249f3577efda74dedf4714fcfab9b3a7

**Comment by DuckMC** [comment]
Thanks for implementing my suggestion! I look forward to seeing this feature soon in the upcoming v2.0.3 release.
