### ISSUE TITLE
[FEATURE REQUEST] Increase Lava Rise Speed at Specified Y-Level

### ISSUE THREAD

**Issue by DuckMC** [goodbyepavlyi/LavaRise#13]
### [FEATURE REQUEST] Increase Lava Rise Speed at Specified Y-Level

**Description:** It would be a great addition to introduce an event that increases the lava rise speed when it reaches a specified Y level.

This feature would allow server administrators to configure an event that triggers when lava reaches a particular Y-coordinate. Upon reaching this threshold, the speed at which the lava rises would increase, adding an extra layer of challenge and excitement for players as they race against the rising lava.

**Edit:** Another possible instead of Y level would be when a certain time has passed that the lava rises faster.

**Comment by goodbyepavlyi** [comment]
Thank you for the suggestion! This feature will be included in the upcoming v2.0.3 release.
Commit: https://github.com/goodbyepavlyi/LavaRise/commit/37ded82849d66a2bb957414c04e56bd3cfcbe64d

**Comment by DuckMC** [comment]
Thanks for implementing my suggestion! I look forward to seeing this feature soon in the upcoming v2.0.3 release.
