### ISSUE TITLE
[FEATURE REQUEST] Display lavaPhaseEnd Event in Scoreboard

### ISSUE THREAD

**Issue by DuckMC** [goodbyepavlyi/LavaRise#14]
### [FEATURE REQUEST] Display lavaPhaseEnd Event in Scoreboard

**Discription:** It would be a valuable enhancement to display the `lavaPhaseEnd` event in the scoreboard when the lava rising stops.

Right now, players may not know exactly when the lava stops rising unless they keep a close eye on the lava level or chat. Displaying the `lavaPhaseEnd` event on the scoreboard gives players an additional visual cue that the lava phase has ended.

**Comment by goodbyepavlyi** [comment]
Thank you for the suggestion! This feature will be included in the upcoming v2.0.3 release. Added a new game phase **Deathmatch**
Commit: https://github.com/goodbyepavlyi/LavaRise/commit/328cb2ed7a672c2f5471a7ecc2fa319ef82bd080

**Comment by DuckMC** [comment]
Thanks for implementing my suggestion! I look forward to seeing this feature soon in the upcoming v2.0.3 release.
