### ISSUE TITLE
[FEATURE REQUEST] Customizable Sound Effects for Events

### ISSUE THREAD

**Issue by DuckMC** [goodbyepavlyi/LavaRise#15]
### [FEATURE REQUEST] Customizable Sound Effects for Events

**Discription:** It would be an excellent enhancement to allow custom, configurable sound effects for specific events, such as playing a dragon sound effect when `pvpEnabled` is triggered. Custom sound effects would improve the user experience by providing immediate, sensory feedback for key events.

This feature allows server administrators to set custom sound effects for specific in-game events. For example, when the `pvpEnabled `or `lavaPhaseStart` event is triggered.

**Comment by goodbyepavlyi** [comment]
Thank you for the suggestion! This feature will be added in the upcoming v2.0.3 release, with support for title/subtitle and sound effects.
Commit: https://github.com/goodbyepavlyi/LavaRise/commit/a65e29ca80eb99b82a65f8233790a13a2cbbd973

**Comment by DuckMC** [comment]
Thanks for implementing my suggestion! I look forward to seeing title/subtitle and sound effects soon in the upcoming v2.0.3 release.
