### ISSUE TITLE
[FEATURE REQUEST]  Customizable Text for %event% Placeholder in Scoreboard

### ISSUE THREAD

**Issue by DuckMC** [goodbyepavlyi/LavaRise#16]
### [FEATURE REQUEST]  Customizable Text for %event% Placeholder in Scoreboard

**Discription:** It would be a valuable addition to allow custom text for the %event% placeholder in the scoreboard or messages, enabling server administrators to set personalized descriptions for different events.

**Comment by goodbyepavlyi** [comment]
Thank you for the suggestion! This feature will be included in the upcoming v2.0.3 release.
Commit: https://github.com/goodbyepavlyi/LavaRise/commit/4ec14e45479b8fcf5ce8a95f3245b2775ea53168

**Comment by DuckMC** [comment]
Thanks for implementing my suggestion! I look forward to seeing this feature soon in the upcoming v2.0.3 release.
