### ISSUE TITLE
[FEATURE REQUEST/QUESTION] Customizable Sound Effects for PvP-enabled

### ISSUE THREAD

**Issue by DuckMC** [goodbyepavlyi/LavaRise#17]
### [FEATURE REQUEST/QUESTION] Customizable Sound Effects for PvP-enabled

**Discription**: It seems that there is currently no title, subtitle, or sound effect associated with the PvP-enabled state. Can you confirm if this is indeed the case? If so, would it be possible to add a title, subtitle and matching sound effect to this event?

Like ‘Lava’ and ‘Deathmatch,’ it would be a valuable addition to have a title, subtitle and sound effect for when PvP is enabled. See also: [#15](https://github.com/goodbyepavlyi/LavaRise/issues/15)

**Comment by goodbyepavlyi** [comment]
Currently, there is no visual effect when PVP is enabled, however, I will include this in the next release.

**Comment by DuckMC** [comment]
Thanks for implementing my suggestion. I look forward to seeing this feature soon in the next release.

**Comment by goodbyepavlyi** [comment]
Thank you for the suggestion! This feature will be included in the upcoming v2.0.4 release.
Commit: fee53d89919eb89205b3e21b1e6de2f4fd3143ad
