### ISSUE TITLE
 [FEATURE REQUEST] Display Titles for Win/Loss Outcomes

### ISSUE THREAD

**Issue by DuckMC** [goodbyepavlyi/LavaRise#18]
### [FEATURE REQUEST] Display Titles for Win/Loss Outcomes

**Description:** It would be a great enhancement to show a title upon match outcomes. When a player loses, a title with “You Lost” could be displayed, and when a player wins, a title with “Victory” could appear.

**Comment by goodbyepavlyi** [comment]
Thank you for the suggestion! This feature will be included in the upcoming v2.0.4 release.
Commit: 11da9544e627247c1bada1418a837ef9e7793c4f

**Comment by DuckMC** [comment]
Thanks for implementing my suggestion!
