### ISSUE TITLE
[FEATURE REQUEST] Placeholders for Map Status and Player Counts (PAPI)

### ISSUE THREAD

**Issue by DuckMC** [goodbyepavlyi/LavaRise#19]
## [FEATURE REQUEST] Placeholders for Map Status and Player Counts (PAPI)

**Description:** I would like to request the addition of several new placeholders for the LavaRise plugin to be used with PlaceholderAPI. These placeholders will provide important information about the game status, the number of players in specific maps, and the total number of players across all maps. 

### **Map Status Placeholder**

- ` %lavarise_map_status_<mapname>%` Returns the current status of a specific map:

**Map status examples:**
Waiting: The map is ready to receive players.
Starting: The game in the map is about to begin.
Active: The game in the map is currently in progress.
Ended: The game in the map has finished and may be resetting.

### **Player Count in a Specific Map**

- `%lavarise_map_players_<mapname>%` Returns the current number of players in a specific map.

### **Total Players Across All Maps**

- `%lavarise_total_players%` Returns the total number of players currently in all active LavaRise maps.

**Comment by goodbyepavlyi** [comment]
Thank you for the suggestion! This feature will be included in the upcoming v2.0.5 release.

Commit: 8ebf2fa74458d53dba33b00e54e446bce29a76f2


## Supported Placeholders:
- `%lavarise_arena_status_<arena_name>%`: Current status of the specified arena.
- `%lavarise_arena_players_<arena_name>%`: Number of players in the specified arena.
- `%lavarise_total_players%`: Total number of players across all arenas.

**Comment by DuckMC** [comment]
Thanks for implementing my suggestion! I look forward to seeing this feature soon in the upcoming v2.0.5 release.
