### ISSUE TITLE
Does this work in 1.21.1?

### ISSUE THREAD

**Issue by Dazee7** [goodbyepavlyi/LavaRise#2]
in my 1.21.1 server i dont know why the lava cant rise, it stuck in Y bottom and not fill it with lava. i wait until 3 minutes and still same not change

**Comment by goodbyepavlyi** [comment]
hello, i have just tested it on a fresh server, and it works as expected for me. could you confirm if the GameArea is set correctly? if possible, could you share the contents of the arenas.yml file?

**Comment by Dazee7** [comment]
Oh sorry it's my fault xD
