### ISSUE TITLE
[BUG]  Players spawn above the lava on random spawn

### ISSUE THREAD

**Issue by DuckMC** [goodbyepavlyi/LavaRise#20]
### [BUG]  Players spawn above the lava on random spawn

**Description:** When players randomly spawn in the map, there is a chance that they spawn above the lava floor. This results in players dying immediately upon spawning. This problem occurs because the spawn logic does not seem to take dangerous areas such as lava into account.

**Additional notes:**
This problem is especially relevant for maps with a dangerous floor, such as lava aera. A possible solution being able to set spawn points. Perhaps the players could spawn high in the air while under the influence of the Slow Falling effect. This way, they gently descend, giving them the opportunity to survey the area below and strategically choose a safe landing spot. Players could even cancel the effect early if they spot a secure location to drop into more quickly.

The version of my server is `1.21.1` and I am using  `LavaRise-2.0.5`

I have recorded a video showing the bug and added an image of the map. Hopefully this will make the problem clear.
https://www.youtube.com/watch?v=h8Vorp5vrwk 

![image](https://github.com/user-attachments/assets/476f7877-6b61-4c65-9850-cfbccaa870f3)

**Edit:** Another example where there is already lava in the map itself.

![image](https://github.com/user-attachments/assets/85bc76c8-6cf5-41c9-925e-22ab7fa039bd)

**Comment by DuckMC** [comment]
**Best solution:** Implement a feature where players spawn in the sky above the map with a slow falling effect. This would allow players to choose their starting location dynamically while descending. It's a unique and engaging way to begin a game, adding an element of strategy and exploration right from the start.

**Comment by goodbyepavlyi** [comment]
Thank you for reporting this issue! This bug should be fixed by the commit 30e40ed825efd71f50c7d4a11afe3d222ca34a53. Can you verify the bug is fixed by using this development version?

---
> [!WARNING]
> Before using the development version I recommend backing up the LavaRise config directory

[LavaRise-2.0.6-dev.jar.zip](https://github.com/user-attachments/files/17963088/LavaRise-2.0.6-dev.jar.zip)

**Comment by DuckMC** [comment]
I added the development version: LavaRise-2.0.6-dev.jar.zip to my server and joined a few games. During these attempts, the bug did not occur again. It seems the bug has been fixed.

**Comment by goodbyepavlyi** [comment]
Great to hear it's fixed! Thank you for testing and confirming the fix.
