### ISSUE TITLE
[FEATURE REQUEST] Message in chat when lava begins to rise.

### ISSUE THREAD

**Issue by DuckMC** [goodbyepavlyi/LavaRise#5]
### [FEATURE REQUEST] Message in chat when lava begins to rise.

**Description:** Add a message in chat when lava begins to rise. This alerts players that the dynamics of the game have changed and that they must take action to survive.

**Comment by goodbyepavlyi** [comment]
Thank you for the suggestion! This feature will be included in the upcoming v2.0.1 release.
Commit: (7c11ddd02f4ccab81aefeb415469b9a4608dbd04)

**Comment by DuckMC** [comment]
Thanks for implementing the requested functionality! I look forward to seeing this feature soon in the upcoming v2.0.1 release.
