### ISSUE TITLE
[FEATURE REQUEST] Message in chat when PvP is enabled.

### ISSUE THREAD

**Issue by DuckMC** [goodbyepavlyi/LavaRise#6]
### [FEATURE REQUEST] Message in chat when PvP is enabled.

**Description:** Add a message in chat that informs players when PvP is enabled, so they are prepared for battles and can adapt to this new event.

**Comment by goodbyepavlyi** [comment]
Thank you for the suggestion! This feature will be included in the upcoming v2.0.1 release.
Commit: (c5e3bf2719ee9a15f0210978cb3bf5230fa7d438)

**Comment by DuckMC** [comment]
Thanks for implementing the requested functionality! I look forward to seeing this feature soon in the upcoming v2.0.1 release.
