### ISSUE TITLE
[FEATURE REQUEST] Ability to customize the leave item.

### ISSUE THREAD

**Issue by DuckMC** [goodbyepavlyi/LavaRise#7]
### [FEATURE REQUEST] Ability to customize the leave item.

**Description:** Add a configuration option that allows the leave item to be customized. This gives more flexibility to server administrators to customize their gameplay and personalize the interface.

**Comment by goodbyepavlyi** [comment]
Thank you for the suggestion! This feature will be included in the upcoming v2.0.1 release.
Commit: (https://github.com/goodbyepavlyi/LavaRise/commit/cb6905ceb7543d14ba0f9b3544dde3c2c2aff335)

**Comment by DuckMC** [comment]
Thanks for implementing the requested functionality! I look forward to seeing this feature soon in the upcoming v2.0.1 release.
