### ISSUE TITLE
[FEATURE REQUEST] Adjustable time before players are teleported out of the map after a game ends.

### ISSUE THREAD

**Issue by DuckMC** [goodbyepavlyi/LavaRise#8]
### [FEATURE REQUEST] Adjustable time before players are teleported out of the map after a game ends.

**Description:** Make the time adjustable for how long it takes before players are teleported out of the map after a game has ended. This allows for the possibility of adding a cooldown period before players return to the lobby.

**Comment by goodbyepavlyi** [comment]
Thank you for the suggestion! This feature will be included in the upcoming v2.0.1 release.
Commit: https://github.com/goodbyepavlyi/LavaRise/commit/4c0cfac5dc87c399efc01423a21b4e45805d52dd

**Comment by DuckMC** [comment]
Thanks for implementing the requested functionality! I look forward to seeing this feature soon in the upcoming v2.0.1 release.
